version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: futo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=futo_marching_dashboard

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: futo-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=futo_marching_dashboard
      - JWT_SECRET=your-secret-key-change-this-in-production
      - PORT=8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: futo-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

volumes:
  mongodb_data: